name: DNAmic Analysis Lint & OS Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  ubuntu:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Application Test - Normal Config
        run: |
          ./DNAmicAnalysis.py tests/normal_test_config.yml
      - name: Check for Excel Output
        run: |
          [ -n "reports/DNAmicAnalysis_cyberarkdemo.com_"* ] && echo "Found" || exit 1
      - name: Remove Excel Output for Next Test
        run: |
          rm -f reports/DNAmicAnalysis_cyberarkdemo.com_*
      - name: Run Application Test - Database Config
        run: |
          ./DNAmicAnalysis.py tests/database_test_config.yml
      - name: Check for Excel Output
        run: |
          [ -n "reports/DNAmicAnalysis_cyberarkdemo.com_"* ] && echo "Found" || exit 1
      - name: Remove Excel Output for Next Test
        run: |
          rm -f reports/DNAmicAnalysis_cyberarkdemo.com_*      

  macos:
    runs-on: macos-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Application Test - Normal Config
        run: |
          ./DNAmicAnalysis.py tests/normal_test_config.yml
      - name: Check for Excel Output
        run: |
          [ -n "reports/DNAmicAnalysis_cyberarkdemo.com_"* ] && echo "Found" || exit 1
      - name: Remove Excel Output for Next Test
        run: |
          rm -f reports/DNAmicAnalysis_cyberarkdemo.com_*
      - name: Run Application Test - Database Config
        run: |
          ./DNAmicAnalysis.py tests/database_test_config.yml
      - name: Check for Excel Output
        run: |
          [ -n "reports/DNAmicAnalysis_cyberarkdemo.com_"* ] && echo "Found" || exit 1
      - name: Remove Excel Output for Next Test
        run: |
          rm -f reports/DNAmicAnalysis_cyberarkdemo.com_*

  windows:
    runs-on: windows-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Application Test - Normal Config
        run: |
          python DNAmicAnalysis.py tests/normal_test_config.yml
      - name: Run Application Test - Database Config
        run: |
          python DNAmicAnalysis.py tests/database_test_config.yml

  mergepal-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.opened
    needs:
      - lint
      - ubuntu
      - macos
      - windows
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@vX.Y.Z
        with:
          token: ${{ secrets.GITHUB_TOKEN }}