name: Deploy

on:
  pull_request:
    types: [closed]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - if: github.event.pull_request.merged
        uses: actions/checkout@v1
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Changes listed in relevant [release project](https://github.com/infamousjoeg/DNAmicAnalysis/projects?query=is%3Aclosed)
          draft: false
          prerelease: true